version: '3.9'

services:
  app:
    build: .
    container_name: php-app
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - app-network

  ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: pdi
      # You should definitely change the password in production
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: app
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
      - app-network
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
  ###< doctrine/doctrine-bundle ###
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5673:5673"
      - "15672:15672"
    networks:
      - app-network
    volumes:
      - "./rabbitmq/logs:/var/log/rabbitmq:rw"
    # Nginx service
  nginx:
    image: nginx:alpine
    container_name: php-nginx
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###