# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    GuzzleHttp\Client:
        class: GuzzleHttp\Client
        arguments:
            - [ ]
    GuzzleHttp\ClientInterface: '@GuzzleHttp\Client'

    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    Symfony\Component\Serializer\Normalizer\ObjectNormalizer:
        arguments:
            - '@serializer.mapping.class_metadata_factory'

    Symfony\Component\Serializer\Encoder\JsonEncoder: ~

    Symfony\Component\Serializer\Serializer:
        arguments:
            - [ '@Symfony\Component\Serializer\Normalizer\ObjectNormalizer' ]
            - [ '@Symfony\Component\Serializer\Encoder\JsonEncoder' ]

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Transaction\Application\Api\:
        resource: '../src/Transaction/Application/Api'
        tags: ['controller.service_arguments']
    App\User\Application\Api\:
        resource: '../src/User/Application/Api'
        tags: ['controller.service_arguments']

    App\Shared\Application\EventListener\ExceptionListener:
        tags: [ kernel.event_listener ]